---
  - name: Copy ldap.conf configuration file
    template: src=ldap.conf.j2 dest={{ ldap_client_path }}/ldap.conf

  - name: Setup nsswitch file
    template: src=nsswitch.conf.j2 dest=/etc/nsswitch.conf

  - name: PAM-common-password configuration file
    template: src=common-password.j2 dest=/etc/pam.d/common-password owner=root group=root mode=0644
    notify:
      - restart nscd

  - name: PAM-common-session configuration file
    template: src=common-session.j2 dest=/etc/pam.d/common-session owner=root group=nslcd mode=0644
    notify:
      - restart nslcd
