---
  - name: Copy ldap.conf configuration file
    template: src=ldap.conf.j2 dest={{ ldap_client_path }}/ldap.conf

  - name: Nscd daemon configuration file
    template: src=nscd.conf.j2 dest=/etc/nscd.conf owner=root group=root mode=0644
    notify:
      - restart nscd

  - name: Nslcd daemon configuration file
    template: src=nslcd.conf.j2 dest=/etc/nslcd.conf owner=root group=nslcd mode=0640
    notify:
      - restart nslcd